### ISSUE TITLE
appveyor

### ISSUE THREAD

**Issue by snmslavk** [riyadparvez/data-structures-csharp#16]
Do you plan to add something like ci.appveyor.com widget or any other improvements to this project? This project is a great repository about c# data structures but I guess that it's dead in terms of improvment and support.

**Comment by riyadparvez** [comment]
Thanks for your interest. Unfortunately I do not see myself investing time in this project in any foreseeable future. I might someday if MS fully embraces Linux. I am looking for someone who can take over this project. Meanwhile, I will be more than happy to accept contributions.
